### ISSUE TITLE
Help needed with Travis -- adding http proxy support

### ISSUE THREAD

**Issue by doccaz** [openSUSE/obs-service-tar_scm#116]
could someone help me here? I'm getting these on Travis:

```
--v-v-- begin STDERR from tar_scm --v-v--
REPOCACHE: /home/travis/build/openSUSE/obs-service-tar_scm/tests/tmp/svn/changesgenerate_corrupt_servicedata/cache
HASH: b3df65c63f2798521380b3cffa60121af932a7884fe338d9a1f35419d2c3e5ce
using /tmp/tmpndADGe
Traceback (most recent call last):
  File "/home/travis/build/openSUSE/obs-service-tar_scm/tests/../tar_scm.py", line 1489, in <module>
    main()
  File "/home/travis/build/openSUSE/obs-service-tar_scm/tests/../tar_scm.py", line 1367, in main
    singletask(use_obs_scm, args)
  File "/home/travis/build/openSUSE/obs-service-tar_scm/tests/../tar_scm.py", line 1398, in singletask
    define_global_scm_command(args.scm)
  File "/home/travis/build/openSUSE/obs-service-tar_scm/tests/../tar_scm.py", line 138, in define_global_scm_command
    re.M | re.I)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
Cleaning: /tmp/tmpndADGe
--^-^-- end   STDERR from tar_scm --^-^--
```

... but these do not occur when I run "make check" locally. What am I doing wrong? It appears to be having trouble understanding a line continuation.

I also may need assistance with some of the unit tests, as the expected command line WILL change depending on whether the http proxy is defined or not.

**Comment by doccaz** [comment]
This is regarding pull request #113 .

**Comment by aspiers** [comment]
@doccaz I think you probably already answered your own question.  If `http_proxy` is not defined in the environment, then `os.environ.get('http_proxy')` will not return a string, causing the `TypeError`.

**Comment by doccaz** [comment]
Thanks! I did fix this. All the NameErrors are gone. It was driving me crazy, but I found out that it was caused by a wrong indent in one function.

I also fixed some unit tests to use the new "global_scm_command". However, I still have 23 assertion errors in in "make check" like these:

`AssertionError: Didn't find /^svn (co|checkout) / in /home/travis/build/openSUSE/obs-service-tar_scm/tests/tmp/svn/switch_revision_and_subdir_no_cache/svn-invocation-02-start-test.log
`
or 

`
AssertionError: 1234571490 != 1234567890
`

Any ideas?

**Comment by doccaz** [comment]
Oh I got it. The regexp is no longer valid due to the extra parameters. Fixing...

**Comment by doccaz** [comment]
I fixed the unit tests to recognize the extra parameters, and it's passing the tests now.
Could someone review it?

**Comment by doccaz** [comment]
I managed to fix the errors, just need someone to review the code. Closing the issue.
