### ISSUE TITLE
required python-yaml is not in SLE12

### ISSUE THREAD

**Issue by olafhering** [openSUSE/obs-service-tar_scm#117]
Maybe an old hat, but:

Problem: nothing provides python-yaml needed by obs-service-tar_scm-0.6.1.1471594222.d257927-121.bax.1.noarch

python-yaml is not in SLE_12.

**Comment by aspiers** [comment]
@olafhering Where did you get that package from?  The correct dependency is `python-PyYAML`, and the [`openSUSE:Tools` `.spec` file](https://build.opensuse.org/package/view_file/openSUSE:Tools/obs-service-tar_scm/obs-service-tar_scm.spec?expand=1) has that.

**Comment by olafhering** [comment]
Perhaps that has been fixed since the time I reported it. Can not double check right now.

**Comment by aspiers** [comment]
OK thanks - I'll close and we can reopen if you see the issue reoccur.
