### ISSUE TITLE
tar_scm with git caching results in no working git in buildhost

### ISSUE THREAD

**Issue by ailin-nemui** [openSUSE/obs-service-tar_scm#118]
If using build.opensuse.org to download my current development state from github, using tar_scm with package-meta=true, then after the implementation of caching, I cannot run any "git" commands  as part of my specfile/debian rules any more. I get the error:

    error: object directory /var/cache/obs/iPZjBpzO5fht/git-cache/.../.git/objects does not exist; check .git/objects/info/alternates.

The reason seems to be that the $builddir/.git folder is mostly empty with only a reference in .git/objects/info/alternates pointing to /var/cache/obs/... (which I guess doesn't exist in the build host)

Here is an example package with this problem: https://build.opensuse.org/package/show/home:ailin_nemui:irssi-git-test/irssi-git

**Comment by ailin-nemui** [comment]
Some further information as discussed on IRC: I grepped the source code of this project and the only reasons I can see that it wants to use git is -- abbreviated -- 

1) "git log > ChangeLog"
2) #define VERSION $(git log -1 --format=%ai)
3) #define USER_VISIBLE_VERSION $(git describe --dirty --long --always --tags) 

I understand it may not be desirable on obs' side to have the whole git objects around and I suppose it shouldn't be too difficult to somehow work around git, maybe with some custom patch in the project for when it is used on obs.

**Comment by ailin-nemui** [comment]
you fixed it

**Comment by aspiers** [comment]
@ailin-nemui Where is the fix?

**Comment by M0ses** [comment]
@aspiers Currently it`s only monkey patched on the source service machine - I will prepare the commit on monday.
