### ISSUE TITLE
exclude uses shell glob pattern, but documentation says regexp

### ISSUE THREAD

**Issue by StefanBruens** [openSUSE/obs-service-tar_scm#124]
Regexp is mentioned here:
https://github.com/openSUSE/obs-service-tar_scm/blob/master/tar_scm.service.in#L102

The pattern is translated by pythons fnmatch.translate before it is used as a regexp.

**Comment by jirislaby** [comment]
The bug still persists even though it's on line 120 now. I was bitten by this bug after more than 2 years after being reported?
