### ISSUE TITLE
Issues running obs_scm service. 

### ISSUE THREAD

**Issue by simotek** [openSUSE/obs-service-tar_scm#141]
I'm guessing its likely I did something wrong here but in case this is a bug

Issue 1:

> simon@tek-master ~/src/obs/openSUSE/X11:Enlightenment:Nightly/efl ➤  osc service run obs_scm                        
> Please specify valid --scm=... options
> 
> Aborting: service call failed:  /usr/lib/obs/service/obs_scm --outdir /home/simon/src/obs/openSUSE/X11:Enlightenment:Nightly/efl/tmpfFw2_L.obs_scm.service
> simon@tek-master ~/src/obs/openSUSE/X11:Enlightenment:Nightly/efl ➤ 

                                          
Issue 2:

> simon@tek-master ~/src/obs/openSUSE/X11:Enlightenment:Nightly/efl ➤ 

> /usr/lib/obs/service/obs_scm --outdir /home/simon/src/obs/openSUSE/X11:Enlightenment:Nightly/efl/tmpfFw2_L.obs_scm.service --scm=git

> Traceback (most recent call last):
>   File "/usr/lib/obs/service/obs_scm", line 28, in <module>
>     main()
>   File "/usr/lib/obs/service/obs_scm", line 25, in main
>     TarSCM.run()
>   File "/usr/lib/obs/service/TarSCM/__init__.py", line 30, in run
>     task_list.process_list()
>   File "/usr/lib/obs/service/TarSCM/tasks.py", line 75, in process_list
>     self._process_single_task(task)
>   File "/usr/lib/obs/service/TarSCM/tasks.py", line 108, in _process_single_task
>     scm_object.fetch_upstream()
>   File "/usr/lib/obs/service/TarSCM/scm/base.py", line 61, in fetch_upstream
>     self._calc_dir_to_clone_to(clone_prefix)
>   File "/usr/lib/obs/service/TarSCM/scm/base.py", line 163, in _calc_dir_to_clone_to
>     url_path = urllib.parse.urlparse(self.url)[2].rstrip('/')
> NameError: global name 'urllib' is not defined
> `

This is on tumbleweed and Leap 42.2 with everything installed from the openSUSE:Tools repo. 

> 
> simon@tek-master ~ ➤  rpm -qi obs-service-tar_scm
> Name        : obs-service-tar_scm
> Version     : 0.7.0.1484082405.7671be8
> Release     : 148.1
> Architecture: noarch
> Install Date: Tue 14 Mar 2017 11:22:42 AM ACDT
> Group       : Development/Tools/Building
> Size        : 135509
> License     : GPL-2.0+
> Signature   : DSA/SHA1, Wed 01 Mar 2017 02:18:38 AM ACDT, Key ID 85753aa5eefefde9
> Source RPM  : obs-service-tar_scm-0.7.0.1484082405.7671be8-148.1.src.rpm
> Build Date  : Wed 01 Mar 2017 02:18:33 AM ACDT
> Build Host  : build84
> Relocations : (not relocatable)
> Vendor      : obs://build.opensuse.org/openSUSE:Tools
> URL         : https://github.com/openSUSE/obs-service-tar_scm
> Summary     : An OBS source service: checkout or update a tar ball from svn/git/hg
> Description :
> This is a source service for openSUSE Build Service.
> 
> It supports downloading from svn, git, hg and bzr repositories.
> Distribution: openSUSE:Tools / openSUSE_42.2
> 
> 

Service file can be found here https://build.opensuse.org/package/view_file/X11:Enlightenment:Nightly/efl/_service?expand=1

**Comment by adrianschroeter** [comment]
1) osc service run obs_scm 

just call it without "obs_scm" argument or specify manually the parameters.

2) url is missing

**Comment by simotek** [comment]
Thanks, figured I was doing something wrong, the URL wasn't missing but was slightly different between the .spec file and the _service file one was git:// while the other was https://
