### ISSUE TITLE
snapcraft is undocumented

### ISSUE THREAD

**Issue by aspiers** [openSUSE/obs-service-tar_scm#156]
Similarly to `obsinfo` in #155, the docs got a bit left behind when the snapcraft functionality was added.  Adding one or two short paragraphs to `README.md` would be great since it would go a long way towards clarifying what it's for and how it works.  Presumably I'm only asking for ~10 minutes of your time ;-)

**Comment by aspiers** [comment]
@M0ses This is mostly resolved by #157, but it is not explained how to use the service.  Are there really no parameters?  You just place a `snapcraft.yml` in the same directory and the service finds out everything it needs from that?

**Comment by M0ses** [comment]
@aspiers Correct - In both snapcraft and appimage the parameters are taken from the corresponding sections in  the yaml files - and both of them can have configured multiple SCM sections with multiple urls configured - so I think adding parameters like we have in obs_scm and tar_scm wouldn`t make any sense. I think, the snapcraft.service and appimage.service should provide sufficient documentation and should be known as the first place when searching for documentation about the parameters of services

**Comment by M0ses** [comment]
@aspiers ping.

Could we close the issue? The best documentation should be snapcraft.service anyway :-)

**Comment by aspiers** [comment]
Sorry, for some reason I am not getting a lot of the email notifications from GitHub for this project which I should - I didn't see this ping :-/

> I think adding parameters like we have in obs_scm and tar_scm wouldn`t make any sense.

Sure, that's fine if the yaml files provide everything required.

> I think, the snapcraft.service and appimage.service should provide sufficient documentation and should be known as the first place when searching for documentation about the parameters of services

I agree that they should, but TBH to me as someone who knows very little about snapcraft and appimage, I still get a slight "WTF" feeling when reading the README for these two `.service` files. I think it could be made better with very little effort, e.g. by hyperlinking to:

- web pages which define the format of these YAML files
- example YAML files

Also the README says "executes the corresponding services" for both services, but what does that actually mean?  Is the source service actually building the snap or the appimage, or is that done as part of the `obs build` later?  I would expect the latter but that sentence makes it sound like the former.

Also, if it's only downloading sources, then why is that service mixed in with this repo which was primarily concerned with building tarballs?  Do the YAML files refer to git repos or something like that?

**Comment by M0ses** [comment]
For the record:
@adrianschroeter : Please correct me if I`m wrong

> Also the README says "executes the corresponding services" for both services, but what does that actually mean? 

It executes the services (or better equivalents), defined in the snapcraft.yml/appimage.yml

> Is the source service actually building the snap or the appimage, 

No, services never build packages

> or is that done as part of the obs build later? I would expect the latter but that sentence makes it sound like the former.

building should be not part of a service.

> 
> Also, if it's only downloading sources, then why is that service mixed in with this repo which was primarily concerned with building tarballs? Do the YAML files refer to git repos or something like that?

Correct. snapcraft.yml and appimage.yml could include the information, where to get the source code (maybe multiple repos) from.

snapcraft/appimage services are only a pointer to the corresponding YAML file which include the information for the services.

Unfortunatly I did not find any links to official documentation for both package formats in the short. Including the current state of development in our doc`s might be a solution, but I fear that the will get outdated soon as both projects are under heavy development.
