### ISSUE TITLE
Exception should be raised when commit timestamps are in future ...

### ISSUE THREAD

**Issue by M0ses** [openSUSE/obs-service-tar_scm#162]
... but a possibilty to overwrite with a parameter and set timestamp to current time should be available.

See also https://github.com/openSUSE/obs-service-tar_scm/pull/131 and https://github.com/openSUSE/obs-service-tar_scm/pull/131/commits/ecab0c1191454301ae5ba6513806a0816bfb04c4

I would suggest to use a parameter --use-current-timestamp or --cut-timestamp

**Comment by M0ses** [comment]
@aspiers @adrianschroeter - Your comments please

**Comment by aspiers** [comment]
What would `--cut-timestamp` do?

And out of curiosity, why would we ever encounter timestamps from the future?

**Comment by M0ses** [comment]
This already happend to some users. It happens mainly if upstream messes up their commit timestamps. E.g. in git we do not use the timestamp of the files in tar archive because even if there was no change the source archive would differ because of different timestamps. The commit timestamp can be used e.g. 
in the version number. '--cut-timestamp' could then be used as a workaround for those who have no possibility to fix the commit timestamps in the upstream project - so at least they could build the package.

**Comment by adrianschroeter** [comment]
On Dienstag, 30. Mai 2017, 15:30:11 CEST wrote Adam Spiers:
> What would `--cut-timestamp` do?
> 
> And out of curiosity, why would we ever encounter timestamps from the future?

when someone did a commit on a system in the future.

We had cases where they were >10 years off and that had the consequence that
zypper won't install any newer submissions for next >10 years (except the version
got increased manually). 

As a result we had to invent a newer, not yet existing version (to avoid Epoch)

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany
