### ISSUE TITLE
Let user choose to include or not the topdir in tar archives

### ISSUE THREAD

**Issue by davidcassany** [openSUSE/obs-service-tar_scm#190]
## Description

In KubernetesCore team we are building our Docker images using KIWI and OBS and we would like to have the sources of our KIWI project at github but we face some difficulties regarding that. Typically any KIWI project is structured as:

- _config.xml_ (the description file)
- _condif.sh_ (the configuration script)
- _root.tar.gz_ (the overlay files)

As it happens [here](https://github.com/openSUSE/docker-containers) the _root.tar.gz_ tarball contains multiple files including scripts, specially in Docker containers where it is not strange to have some entrypoint script there. We would like to have this _root.tar.gz_ file uncompressed at github as it may include some code specific for the repo which is not present in anywhere else, thus it is so convenient to be able to make PR and reviews in a regular way in that case. I have been trying to use _obs_scm_ service to build _root.tar.gz_ file on the fly, assuming a _root_ folder in the github repo with the following configuration:

```xml
<services>
    <service name="obs_scm" mode="disabled">
        <param name="url">https://github.com/davidcassany/docker-containers.git</param>
        <param name="scm">git</param>
        <param name="subdir">openSUSE-Tumbleweed</param>
        <param name="revision">switch_to_kiwi-ng-uncompressed-root</param>
        <param name="extract">config.kiwi</param>
        <param name="extract">config.sh</param>
    </service>
    <service name="tar" mode="disabled">
        <param name="subdir">openSUSE-Tumbleweed/root</param>
        <param name="filename">root</param>
        <param name="extension">tar.gz</param>
    </service>
</services>
```
This configuration creates the file _root.tar.gz_ and it is almost what we need, but there is an issue. The resulting root.tar.gz file includes the top directory (in this case the _root_ folder) in it. KIWI expands _root.tar.gz_ in `/` of the root tree image, thus in this case the top directory should not be included.

I am wondering if it would make sense to include a new parameter for the tar service in order to include or not the top directory, something like:

```xml
...
<service name="tar" mode="disabled">
    <param name="subdir">openSUSE-Tumbleweed/root</param>
    <param name="filename">root</param>
    <param name="extension">tar.gz</param>
    <param name="include_topdir">no</param>
</service>
```

Does it make any sense to you? I would expect _include_topdir_ enabled by default. I could try to provide a patch for it, but I'd like to know your opinion before investing some time on it.

**Comment by aspiers** [comment]
Thanks for the great report! Yes, this makes sense to me. I see you're still working on fixing the tests for #191 but I look forward to reviewing a working version when it's ready :-)

**Comment by davidcassany** [comment]
Tests are green again 😃 

By the way, are you sure we still need to support python2.6? I tried to set a python2.6 env for a proper local testing as travis is doing and I got mad trying so, this is quite old and unsupported upstream.

**Comment by aspiers** [comment]
Great! Last I heard, we do still need 2.6 :-/  See #145.

**Comment by davidcassany** [comment]
I am closing this issue, since another solution is proposed here:

openSUSE/docker-containers#73

Thus this should not appears in the issues list anymore 😃
