### ISSUE TITLE
Using CACHEDIRECTORY breaks obs_scm

### ISSUE THREAD

**Issue by vuntz** [openSUSE/obs-service-tar_scm#202]
I have this:

```
$ cat ~/.obs/tar_scm
[tar_scm]
CACHEDIRECTORY="/home/vuntz/.cache/obs/tar_scm"
```

When I do `osc service dr` on some crowbar package, I get:

```
Detected cached repository...
debc21eb6fb2d59daa2584c6c9ebf730717701e3
fatal: destination path '/home/vuntz/ibs/Devel:Cloud:8:Staging/crowbar-init' already exists and is not an empty directory.
ERROR(128): "fatal: destination path '/home/vuntz/ibs/Devel:Cloud:8:Staging/crowbar-init' already exists and is not an empty directory."
Command failed(128): "fatal: destination path '/home/vuntz/ibs/Devel:Cloud:8:Staging/crowbar-init' already exists and is not an empty directory."
Aborting: service call failed:  /usr/lib/obs/service/obs_scm --url git://github.com/crowbar/crowbar-init.git --scm git --filename crowbar-init --versionformat 5.0+git.%ct.%h --revision master --submodules disable --changesgenerate enable --outdir /home/vuntz/ibs/Devel:Cloud:8:Staging/crowbar-init/tmp7XT3Wj.obs_scm.service
```

The failure is actually a git failure, and this is the command that fails (called from `prepare_working_copy`):
```
['git', 'clone', '--reference', '/home/vuntz/.cache/obs/tar_scm/e3a48d27add53c51a83d0846a20a41da527434786c9e78d04b3d45d4ac1a1a27/crowbar-init', 'git://github.com/crowbar/crowbar-init.git', '/home/vuntz/ibs/Devel:Cloud:8:Staging/crowbar-init']
```

I suspect the last argument should probably be a subdirectory of the package dir, not the package dir itself...

**Comment by vuntz** [comment]
I forgot to mention: everything works fine as soon as I drop my tar_scm config file.

**Comment by aspiers** [comment]
OHHHHH ... :-/  (*sound of light bulb going on*)

Is this maybe a clash between [the automatic unpacking](https://github.com/aspiers/obs-service-tar_scm/blob/d5d422e3357133b2756077c3cf7d63e611a80381/README.md#obs_scm) of an `.obscpio` [inside the checked-out project](http://openbuildservice.org/2016/04/08/new_git_in_27/), and the fact that `obs_scm` in `disabled` mode also expects to be able to clone the remote repository into the same location?

**Comment by aspiers** [comment]
Hrm, but why would enabling the cache cause this?  @vuntz Are you 100% sure it's the cache which breaks it, and not this clash?

**Comment by vuntz** [comment]
> @vuntz Are you 100% sure it's the cache which breaks it, and not this clash?

The only thing I'm sure about is that removing my config file is fixing it. And the reason it's fixing it is that the `prepare_working_copy` method is not used (iirc) because it's skipped if there's no cache directory.

So it could be that you're correct, but that it only becomes visible when that method is used...

**Comment by aspiers** [comment]
@vuntz Any chance you could test whether #203 fixes it? Because it sounds like the same problem.

**Comment by vuntz** [comment]
> @vuntz Any chance you could test whether #203 fixes it? Because it sounds like the same problem.

It does fix it.
