### ISSUE TITLE
Add tag signature verification

### ISSUE THREAD

**Issue by cryptomilk** [openSUSE/obs-service-tar_scm#220]
Please add the possibility to verify signed tags!

**Comment by aspiers** [comment]
Sounds like a cool idea; please could you give more details about how you would expect this to work? e.g. what would a sample `_service` file look like?

**Comment by aspiers** [comment]
Hrm, actually I think this is a duplicate of #127, so let's continue the discussion there.  (If you disagree we can easily reopen this.)
