### ISSUE TITLE
Release wanted

### ISSUE THREAD

**Issue by Ana06** [openSUSE/obs-service-tar_scm#234]
Can you please release a new version which includes https://github.com/openSUSE/obs-service-tar_scm/commit/bfd5d1cb28410ad5f297206d14ae4d09d544d755 ? :pray: 

I also get the error.... :sob:

**Comment by adrianschroeter** [comment]
On Mittwoch, 25. April 2018, 11:42:59 CEST wrote Ana María Martínez Gómez:
> Can you please release a new version which includes https://github.com/openSUSE/obs-service-tar_scm/commit/bfd5d1cb28410ad5f297206d14ae4d09d544d755 ? :pray: 
> 
> I also get the error.... :sob: 

the current code is in openSUSE:Tools project as package.


-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by Ana06** [comment]
but it would be nice that it is automatically updated when doing `zypper up obs-service-tar_scm` (added to factory) without having to find out where the correct version is... :thinking: Although I don't know if this is the correct place to ask this...

**Comment by Ana06** [comment]
@adrianschroeter thanks!
