### ISSUE TITLE
Missing license content

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/obs-service-tar_scm#257]
This source service is labeled as `GPL-2.0-or-later` in the packaging, but there's no license file for the GPLv2, nor is the requisite header in the source files present. Can this be fixed, please?

This is necessary for me to package this source service in Fedora.

**Comment by coolo** [comment]
this should be really trivial to fix and you're violating your own license atm.

**Comment by adrianschroeter** [comment]
done in master now.
