### ISSUE TITLE
osc service dr no longer picks up the changesauthor from .oscrc

### ISSUE THREAD

**Issue by krig** [openSUSE/obs-service-tar_scm#296]
Due to this commit:

https://github.com/openSUSE/obs-service-tar_scm/commit/ae7a853979c34210bd67720382b5c6eb2d1e8ba0#diff-5eff1b270461a753c1ea7ab6ac8e4dab

by @M0ses,

I now get this error when running `osc service dr`:

```
No changesauthor defined!
You can define it by:
 * configure 'email=' in ~/.config/osc/oscrc in your default api section
 * configure <param name="changesauthor">...</param> in your _service file
 * using '--changesauthor' on the cli
```

Out of these suggested solutions, the first one doesn't work (I have email= configured correctly in `.oscrc`), the second one is not viable for packages with multiple maintainers, and the last one is not possible when running via `osc`.

To me it looks like the code that was removed starting at line 212 in changes.py did exactly the first part - picking up the email from `.oscrc`.

**Comment by krig** [comment]
It's possible that this was broken by a change in osc:

https://github.com/openSUSE/osc/pull/368

Seems it no longer exports `VC_MAILADDR` but `mailaddr`.

**Comment by Conan-Kudo** [comment]
@krig It's supposed to export both.

**Comment by krig** [comment]
> @krig It's supposed to export both.

It doesn't for me... if I do `VC_MAILADDR=kgronlund@suse.com osc service dr` everything works, but if I don't, I get the error message from the service.

**Comment by Conan-Kudo** [comment]
Maybe it was dropped in a future PR? I definitely exported it with my original PR.

**Comment by krig** [comment]
Yeah, I see that there is code that is supposed to export it.. no idea why it stopped working.

**Comment by M0ses** [comment]
@krig : which version of osc/obs-service-tar_scm do you use?

**Comment by krig** [comment]
obs-service-tar_scm-0.10.5.1551309990.79898c7-lp150.2.3.1.noarch
osc-0.162.1-lp150.1.3.noarch

**Comment by marcus-h** [comment]
On 2019-03-25 17:57:28 -0700, Kristoffer Grönlund wrote:
> obs-service-tar_scm-0.10.5.1551309990.79898c7-lp150.2.3.1.noarch
> osc-0.162.1-lp150.1.3.noarch
>
The osc version is not recent enough. As a workaround, you can get a
recent version from the openSUSE:Tools repo.

**Comment by M0ses** [comment]
should work with osc >= 0.163.0

VC_MAILADDR was invoked with https://github.com/openSUSE/osc/commit/ef13d67

So it cannot work. 
Maybe we should add this to the help text.

**Comment by krig** [comment]
Yes, that would help.

**Comment by krig** [comment]
So, for clarity: These are the versions of `osc` and `obs-service-tar_scm` that are currently in Leap 15. So anyone using the packages from Leap 15 have a broken combination of `osc` and the `tar_scm` service.

**Comment by M0ses** [comment]
@marcus-h @lethliel 

Do you plan to release a new osc version in near future for openSUSE >= 15.0?

**Comment by lethliel** [comment]
I will release a new version this week

**Comment by lethliel** [comment]
new osc version release. This can be closed.
