### ISSUE TITLE
locale issue on CentOS 7

### ISSUE THREAD

**Issue by matthewdva** [openSUSE/obs-service-tar_scm#326]
version 0.10.10 has introduced a locale issue when run on CentOS 7.

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 1079: invalid continuation byte`
This error occurs in both python2.7 and python3

The attached patch corrects the issue but admittedly may not be the correct approach.

[locale-decode.patch.gz](https://github.com/openSUSE/obs-service-tar_scm/files/3562077/locale-decode.patch.gz)

**Comment by pseiler** [comment]
I can verify this: Here is a build log which reproduces this error: 
https://bauleiterk001.srv.muenchen.de/package/live_build_log/Systemmanagement/mia-scripts/RHEL_7/x86_64

**Comment by lethliel** [comment]
@matthewdva @pseiler 
Thanks for the report. I found the reason. There is `bokmål` in the output of `locale -a` (at least for RHEL7)

Regarding your patch: It works, but i personally don't like "hard coding" the encoding we assume.
So I submitted a PR with another approach. I don't know which approach the maintainer of obs-service-tar_scm likes better. 

@M0ses: Your thoughts?

**Comment by juliogonzalez** [comment]
I can confirm the same problem at CentOS6. #333 fixes it (after applying my patch from #335)

**Comment by matthewdva** [comment]
@lethliel 
Thank you for getting to the root issue.  I too did not like the concept of my own patch.  I did not want report a problem without a providing a possible solution.  For what it is worth I think your PR is much better than mine.
