### ISSUE TITLE
Could not use obs_scm to clone gitlab source errno=Network is unreachable

### ISSUE THREAD

**Issue by kevinsmia1939** [openSUSE/obs-service-tar_scm#358]
Hello, I tried using _service on openSUSE Tumbleweed to download source code from
`https://git.jami.net/savoirfairelinux/ring-project`

But I get this error

```
Command failed(128): 'Cloning into '/home/kev-test/Desktop/Software/OBS Projects/home:andythe_great/Jami/ring-project'...
fatal: unable to connect to git.jami.net:
git.jami.net[0: 184.95.250.230]: errno=Connection timed out
git.jami.net[1: 2607:fad8:4:6:5054:ff:fe8c:f804]: errno=Network is unreachable
```
Does obs_scm support download from gitlab repo like this?

Thanks.

This is the content of the spec file.
```
 <services>
  <service mode="localonly" name="obs_scm">
    <param name="url">git://git.jami.net/savoirfairelinux/ring-project.git</param>
    <param name="scm">git</param>
    <param name="submodules">enable</param>
    <param name="revision">0d5117e2</param>
    <param name="versionprefix">202001+git</param>
    <param name="versionformat">%ct.%h</param>
  </service>
  <service mode="buildtime" name="tar" />
  <service mode="buildtime" name="recompress">
    <param name="file">*.tar</param>
    <param name="compression">xz</param>
  </service>
  <service mode="localonly" name="set_version" />
</services>
```

**Comment by marcus-h** [comment]
On 2020-04-12 06:00:10 -0700, Kevin Tee wrote:
> Hello, I tried using _service on openSUSE Tumbleweed to download source code from
> `https://git.jami.net/savoirfairelinux/ring-project`
>
> But I get this error
>
> ```
> Command failed(128): 'Cloning into '/home/kev-test/Desktop/Software/OBS Projects/home:andythe_great/Jami/ring-project'...
> fatal: unable to connect to git.jami.net:
> git.jami.net[0: 184.95.250.230]: errno=Connection timed out
> git.jami.net[1: 2607:fad8:4:6:5054:ff:fe8c:f804]: errno=Network is unreachable
> ```
> Does obs_scm support download from gitlab repo like this?
>
In general, yes but this a remote error. Cloning via https works
for me: git clone https://git.jami.net/savoirfairelinux/ring-project.git

If cloning via https is OK for you, just change the "url" param in the
_service file.

**Comment by kevinsmia1939** [comment]
thanks that work
