### ISSUE TITLE
nothing provides obs-service-tar CentOS 

### ISSUE THREAD

**Issue by olegantonyan** [openSUSE/obs-service-tar_scm#369]
Project: https://build.opensuse.org/project/show/home:oleg_antonyan
Package: https://build.opensuse.org/package/show/home:oleg_antonyan/mpz
`_service` file:
```
<services>
  <service name="obs_scm">
    <param name="scm">git</param>
    <param name="url">https://github.com/olegantonyan/mpz.git</param>
    <param name="versionformat">@PARENT_TAG@.@TAG_OFFSET@</param>
    <param name="filename">mpz</param>
    <param name="extract">mpz.spec</param>
    <param name="extract">debian.control</param>
    <param name="extract">debian.rules</param>
    <param name="extract">debian.compat</param>
    <param name="extract">mpz.dsc</param>
    <param name="extract">debian.changelog</param>
  </service>
  <service mode="buildtime" name="tar" />
  <service mode="buildtime" name="recompress">
    <param name="file">*.tar</param>
    <param name="compression">gz</param>
  </service>
  <service mode="buildtime" name="set_version"/>
</services>
```

Most recent distros work fine, but CentOS 8 and old Ubuntu give an unresolvable error "nothing provides obs-service-tar". I suppose this service is provided by `obs-service-tar_scm` which is already linked into my project and it works for other distros.

I couldn't find separate package for `obs-service-tar`.

What's wrong here?

**Comment by luc14n0** [comment]
I see that nowadays we have an `obs-service-tar` in the [download repo](https://download.opensuse.org/repositories/openSUSE:/Tools/CentOS_8/noarch/). Can we close this one then? Whatever was going on before, back in Aug 2020, that wasn't either producing binaries or publishing them seem to be resolved.
