### ISSUE TITLE
obscpio without version?

### ISSUE THREAD

**Issue by lnussel** [openSUSE/obs-service-tar_scm#389]
When using tar_scm in disabled mode to generate a obscpio file, the file name includes the version number. That makes it cumbersome to update as one has to osc rm and osc add. How about omitting the version number when creating an obscpio file? The file name is not visible in the build rpm/srpm after all.

Eg `cockpit-235+git20210121.93e24f4c6.obscpio ` should be just `cockpit.obscpio`. The directory it contains still needs to be `cockpit-235+git20210121.93e24f4c6` and the version in the obsinfo needs to be correct too.

That way the built rpm has version `235+git20210121.93e24f4c6` and also the tarball in the srpm has it. Nevertheless a simple `osc service dr` followed by `osc ci` would be sufficient to update a package from git.

**Comment by adrianschroeter** [comment]
it needs at least extracted as cockpit-235+git20210121.93e24f4c6 for the tar'ing

I would not really like to change this, since it it would be incompatible and break usages where multiple versions of sources are checked in.

However, it should be possible to change to "cockpit" via filename parameter IIRC?

**Comment by adrianschroeter** [comment]
obsinfo is anyway fresh generated and set_version is updating spec file. 

We could consider a functionality to remove the former file automatically though.

**Comment by lnussel** [comment]
the filename parameter would also change the directory and tarball name at build time means spec can't have the original tarball referenced. There wouldn't be an incompatibility as enabling this feature would require an extra parameter anyway.
But sure, removing the old file would also be good. In any case. That prevents forgetting it.
