### ISSUE TITLE
how to make obs_scm re-fetch from git?

### ISSUE THREAD

**Issue by stsp** [openSUSE/obs-service-tar_scm#408]
This may be not the right place
to ask such question, but any help
is appreciated.
I am using obs_scm to fetch from
github. It creates the .obsinfo and
.obscpio files that I can't remove
from the gui. If I retrigger the build,
it takes this previously fetched copy.
How can I remove these files or
ask obs_scm to re-fetch from upstream?

**Comment by M0ses** [comment]
Better ask in #opensuse-buildservice channel on freenode or the buildservice@lists.opensuse.org mailing list next time.

Could you post an URL to the affected project/package/repository in OBS?

**Comment by stsp** [comment]
I actually found the work-around already,
which is `osc token --trigger <token>`.
I just find that a bit annoying and
counter-intuitive that one can't remove
the cached files.
