### ISSUE TITLE
#39 needs integration test

### ISSUE THREAD

**Issue by aspiers** [openSUSE/obs-service-tar_scm#41]
I merged #39 even though it didn't contain tests, which was a mistake according to the [contributor's guidelines](https://github.com/openSUSE/obs-service-tar_scm/blob/master/CONTRIBUTING.md).  @thorstenb please can you add tests?

**Comment by aspiers** [comment]
Hmph, well this is proof why a project maintainer should never feel embarrassed about refusing PRs due to lack of corresponding tests :-/

**Comment by thorstenb** [comment]
oh shoot - dropped the ball on that one, let me have a quick look tonite -
