### ISSUE TITLE
dashes not removed from commit date when versionrewrite-pattern used

### ISSUE THREAD

**Issue by hramrach** [openSUSE/obs-service-tar_scm#419]
```
<services>
        <service name="obs_scm" mode="localonly">
                <param name="scm">git</param>
                <param name="url">https://github.com/open-power/secvarctl.git</param>
                <param name="revision">main</param>
                <param name="versionformat">@PARENT_TAG@+git@TAG_OFFSET@_%cd_%h</param>
                <param name="changesgenerate">enable</param>
        </service>
        <service name="tar" mode="localonly" />
        <service name="recompress" mode="localonly">
        <param name="file">*.tar</param>
        <param name="compression">xz</param>
        </service>
        <service name="set_version" mode="localonly" />
</services>
```
Version:        v0.2+git20_20210525_652c950
```
<param name="versionrewrite-pattern">v(.*)</param>
```
Version:        0.2+git20_2021-05-25_652c950

**Comment by M0ses** [comment]
Why should it remove dashes from the commit date?

I will quote here my commit message from https://github.com/openSUSE/obs-service-tar_scm/pull/390/commits/49bb443c6011f0a4da0469e37cbbe7df1f0e4b97

```
If versionrewrite_pattern is used we assume you know what you are doing.
If it is not set we sanitize the version at the end avoid corrupt spec
e.g if version hyphens.
```
We did not change the default behaviour as it might break tons of existing setups - but we disabled sanitizing if versionrewrite_pattern is set because versionrewrite_pattern is an advanced feature for advanced users.

**Comment by hramrach** [comment]
This is not about dashes that are injected from the tag but dashes that are injected from the date by the service itself.

The date is documented as `%cd` `YYYYMMDD` but it may become `YYYYMMDD` or `YYYY-MM-DD` depending on presence of `versionrewrite_pattern`. This behavior does not make any sense whatsoever and is in conflict with documentation.

**Comment by M0ses** [comment]
This is what you might be looking for:

```
                <param name="versionrewrite-pattern">v(.*_)(\d{4})-(\d{2})-(\d{2})(_.*)</param>
                <param name="versionrewrite-replacement">\1\2\3\4\5</param>
```

Keep in mind that our services cannot only be used to prepare RPM packaging. Dashes might be bad in RPM version numbers but not in other formats.

**Comment by M0ses** [comment]
There gets nothing injected. 

I would also prefer to get rid of sanitizing the version string at all - but this would be a regression which would affect tons of projects - all relying on the current behaviour that dashes are removed from %cd - as all other dashes.

This is why it looks so inconsistent when comparing output with/without "versionrewrite-pattern".

**Comment by hramrach** [comment]
no, that's definitely not what I am looking for.

The version is `@PARENT_TAG@+git@TAG_OFFSET@_%cd_%h` and your `versionrewrite-pattern` does not account for the `+git@TAG_OFFSET@_` part so it will not match.

At any rate `%cd` is documented to produce `YYYYMMDD` so it should always produce that output regardless of presence of versionrewrite-pattern

**Comment by M0ses** [comment]
> At any rate `%cd` is documented to produce `YYYYMMDD` so it should always produce that output regardless of presence of versionrewrite-pattern

where?

**Comment by hramrach** [comment]
> There gets nothing injected.
Clearly there is.
My `versionformat` is `@PARENT_TAG@+git@TAG_OFFSET@_%cd_%h` git also happens to have `%cd` format specifier but it produces something like `Thu Jun 10 18:38:06 2021 +0200` not `YYYYMMDD` nor `YYYY-MM-DD`. So that date is injected by the service, and then it should be fixed to work as documented regardless of `versionrewrite-pattern`.
> 
> I would also prefer to get rid of sanitizing the version string at all - but this would be a regression which would affect tons of projects - all relying on the current behaviour that dashes are removed from %cd - as all other dashes.\

And because it is documented that `%cd` has no dashes it should continue to have no dashes regardless of `versionrewrite-pattern`.

> This is why it looks so inconsistent when comparing output with/without "versionrewrite-pattern".

It does not only look in consistent, it is inconsistent.

**Comment by hramrach** [comment]
> > At any rate `%cd` is documented to produce `YYYYMMDD` so it should always produce that output regardless of presence of versionrewrite-pattern
> 
> where?

https://github.com/openSUSE/obs-service-tar_scm/blob/master/tar_scm.service.in#L83

**Comment by M0ses** [comment]
> Clearly there is.

Is it? Try yourself if you do not trust in me:

``` 
git log -n1 --date=short --pretty=format:"%s  %cd"
```

**Comment by hramrach** [comment]
> > Clearly there is.
> 
> Is it? Try yourself if you do not trust in me:
> 
> ```
> git log -n1 --date=short --pretty=format:"%s  %cd"
> ```

Then you have specified arbitrary format for date. You can as well specify it so that it does not produce dashes.

**Comment by M0ses** [comment]
Thanks for your hint to a wrong documentation. I have to admit that some more explaination there would be helpful

**Comment by M0ses** [comment]
> Then you have specified arbitrary format for date. You can as well specify it so that it does not produce dashes.

Look into the code if you don`t want to trust me:

https://github.com/openSUSE/obs-service-tar_scm/blob/master/TarSCM/scm/git.py#L255

**Comment by hramrach** [comment]
> > Then you have specified arbitrary format for date. You can as well specify it so that it does not produce dashes.
> 
> Look into the code if you don`t want to trust me:
> 
> https://github.com/openSUSE/obs-service-tar_scm/blob/master/TarSCM/scm/git.py#L255

yes, it specifies arbitrary date format which produces date with dashes and was relied to be stripped of the dashes previously

**Comment by M0ses** [comment]
Here is the line where the dashes get removed - https://github.com/openSUSE/obs-service-tar_scm/commit/49bb443c6011f0a4da0469e37cbbe7df1f0e4b97#diff-9e5422cb941d4a78a946729b9ca129fd59ca5d215b58f9ebbf8354e056c5b3bdR276

**Comment by hramrach** [comment]
So if you specify `--date=format:%Y%m%d` instead of `--date=short` it will work as documented and fix the regression with `versionrewrite-pattern`

**Comment by M0ses** [comment]
Yep - but it  would break other peoples repositories who have now working regex.

@adrianschroeter Any strong opinions about this issue?

**Comment by M0ses** [comment]
> The version is `@PARENT_TAG@+git@TAG_OFFSET@_%cd_%h` and your `versionrewrite-pattern` does not account for the `+git@TAG_OFFSET@_` part so it will not match.

looks ok for me:

```
> osc service lr
Already up to date.
652c950e030a0053735929c7ce6ee898d0979ea7
Compressed secvarctl-0.2+git20_20210525_652c950.tar to secvarctl-0.2+git20_20210525_652c950.tar.xz
```

**Comment by hramrach** [comment]
> Yep - but it would break other peoples repositories who have now working regex.

I somewhat doubt it. Sure, every time you introduce a bug it is possible that some users will rely on the broken behavior.

However, doing the tag rewrites is not very common in the first place, and many packages use the seconds since epoch or no date at all. I also dropped the date from the package version because it was formatted incorrectly.

**Comment by seife** [comment]
This certainly is a regression.
```
    <param name="versionformat">@PARENT_TAG@.@TAG_OFFSET@+%cd~%h</param>
    <param name="versionrewrite-pattern">v(.*)</param>
```

This worked as expected (%cd expanding to 20210506) with 0.10.16.1595245235.15a0df2 and breaks with 0.10.22.1615538418.07a353d (yes, I did not update our tar_scm package for quite some time ;-))

It also violates the documented behaviour from tar_scm.service:
```
      %cd               Commit date in YYYYMMDD format, e.g. 20131119
```

I'd say the usage pointed out above is pretty common, as you need versionrewrite-pattern for common github tags, but might still want to have a commit date for easy identification.
For our instance this is breaking lots of packages.

**Comment by M0ses** [comment]
I had a deeper look in that issue and came to the conclusion - Better have a consistent behavior and risk a regression for _some_ packages then live with an inconsistent behavior forever - so I will merge the PR.

Additional note: Their might be regressions for some packages in OBS - but I found only about 20+ packages from over 20000+ which will be potentially affected.
