### ISSUE TITLE
tar_scm puts dashes in the date field

### ISSUE THREAD

**Issue by lgbaldoni** [openSUSE/obs-service-tar_scm#423]
Using tar_scm in a _service with `versionformat` as `@PARENT_TAG@+git%cd.%h`: the latter expands to e.g. `0.7.0+git2021-05-30.c45f323` and then `set_version` gets confused and puts `30.c45f323` in the spec file.
It has started happening a few months ago, unsure how to proceed.

**Comment by bluca** [comment]
this was fixed by https://github.com/openSUSE/obs-service-tar_scm/pull/421

**Comment by lgbaldoni** [comment]
Indeed. This can be closed.
