### ISSUE TITLE
unresolvable: have choice for bzr needed by obs-service-tar-scm: brz bzr

### ISSUE THREAD

**Issue by frederic-loui** [openSUSE/obs-service-tar_scm#432]
Hi, I managed to create a successful build for Debian 11 and Debian Unstable [here](https://build.opensuse.org/package/show/home:frederic-loui:p4lang:PI:main/p4lang-pi),  but for Debian Testing i get this error:
`unresolvable: have choice for bzr needed by obs-service-tar-scm: brz bzr`

I tried my favorite search engine but no luck in finding any hints ...

Any idea ?

![Capture d’écran 2021-11-04 à 11 16 19](https://user-images.githubusercontent.com/9639687/140296731-a6aa57fa-af6d-4e5a-b443-98aeb540412c.png)

**Comment by M0ses** [comment]
This is not a problem of the package. Seems like Debian testing has 2 packages which provide "bzr"
You need a `Prefer` statement in your prjconf:

https://build.opensuse.org/projects/home:frederic-loui:p4lang:PI:main/prjconf

e.g.

`Prefer: bzr`

or as de-prefer:

`Prefer: -brz`

depending on which package you would like to use while building.
