### ISSUE TITLE
obs_scm seems to broken on CentOS_8

### ISSUE THREAD

**Issue by Masgalor** [openSUSE/obs-service-tar_scm#450]
I'm not sure if this is a problem with this package or with build.opensuse.org or maybe with CentOS itself.
But I also don't know where else to ask for help, so feel free to close this issue if it is inappropriate.

For some time now my builds for CentOS_8 and CentOS_8_Stream are failing when `<service name="tar" mode="buildtime">` is used.

Because some (maybe all?) obs-services are not present in the official repository I added `openSUSE:Tools/CentOS_8`.
During build initialization the required packes for this service are installed.
```
[   82s] [389/413] installing obs-service-obs_scm-common-0.10.30.1641990734.bdad8f9-314.14
[   84s] [400/413] installing obs-service-tar-0.10.30.1641990734.bdad8f9-314.14
```

But it fails anyway with this error:
```
[   87s] Running build time source services...
[   87s] Can't exec "/usr/lib/obs/service/tar": No such file or directory at /.build/runservices line 87.
[   87s] /usr/lib/obs/service/tar: No such file or directory
[   87s] service run failed for service 'tar'
```

Project-[Link](https://build.opensuse.org/project/show/home:Masgalor:Vaultwarden_staging) for reference.

**Comment by M0ses** [comment]
Seems like an CentOS 8 problem. obs-service-tar_scm requires e.g. python3-pyyaml (and other python3 modules) but they don`t require python3. 
On CentOS 8 they require "python(abi) = 3.6" 
  * which is provided by platform-python-3.6.8-41.el8.x86_64
    * which does not contain "/usr/bin/python3"

**Comment by Masgalor** [comment]
Hi @M0ses ,
thank you for your efforts solving this issue.

Unfortunatly, I have to report that my builds at `build.opensuse.org` fail the same way they did before.
```
[   72s] [404/417] installing obs-service-obs_scm-common-0.10.32.1662712308.31d1884-315.1
[   72s] [409/417] installing obs-service-tar-0.10.32.1662712308.31d1884-315.1

[   77s] Running build time source services...
[   77s] Can't exec "/usr/lib/obs/service/tar": No such file or directory at /.build/runservices line 87.
[   77s] /usr/lib/obs/service/tar: No such file or directory
[   77s] service run failed for service 'tar'
```

For now I added `python3` as a build dependency to my spec-file.
```
%if 0%{?centos_version} > 700
BuildRequires: python3
%endif
```
This way the source-service is run as expected and my build succeeds.

If I can provide anything else to help with this problem I am happy to do so.

**Comment by M0ses** [comment]
@Masgalor  Could you please provide a link to your prj/pkg on build.opensuse.org - this would make debugging much easier (maybe you only need to rebuild the package as we did some changes in the prjconf of CentOS:CentOS-8 at friday)

**Comment by Masgalor** [comment]
There is a link to my project in the initial issue description (at the very end of it).

Should I undo my last change to the spec, so it will fail again?

**Comment by M0ses** [comment]
Yes, please revert it so we can see if the error persists and if so we can debug it.

**Comment by Masgalor** [comment]
I reverted my previous changes to the spec-file.
The builds for CentOS_8 and CentOS_8_Stream have faild again.

I may be slow to respond the next few hours, but if I can do something to help, just let me know.

**Comment by M0ses** [comment]
Should work now
