### ISSUE TITLE
Service broken if .lock file left over by previous versions

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/obs-service-tar_scm#453]
Previous versions of this service never cleaned up their created `.lock` files. That was just a minor issue as it also didn't care that the lock was there.

Now it's different though: If the `.lock` file is there, it'll just wait forever. Because the older versions never cleaned them up properly, this will affect a lot of checkouts.

**Comment by v-fox** [comment]
Damn it, because of this I almost got gaslit into believing that there is some kind of weird networking problem or corrupt installation. Such an absurd behaviour.

**Comment by uncomfyhalomacro** [comment]
experienced this recently and i also found this behavior absurd
