### ISSUE TITLE
Causes "unresolvable" error for Fedora 34+

### ISSUE THREAD

**Issue by zilti** [openSUSE/obs-service-tar_scm#455]
For Fedora 34 and later, a dependency needs to be fixed for obs_scm:
```
 unresolvable: have choice for (glibc-langpack-en or glibc-all-langpacks) needed by obs-service-obs_scm-common: glibc-all-langpacks glibc-langpack-en 
```

**Comment by M0ses** [comment]
You can fix this for your project in OBS by setting a prefer or de-prefer in the project config. e.g.

```
osc meta prjconf -e

# enter in the file a line like

Prefer: -glibc-all-langpacks 
```

**Comment by zilti** [comment]
Shouldn't tar_scm set a preference already on its own? I think obs services should be as unintrusive as possible in that regard, as in I shouldn't have to alter the project config to use it.
That, or `glibc-all-langpacks` should be in the default value for the prjconf Prefer.

**Comment by M0ses** [comment]
> Shouldn't tar_scm set a preference already on its own?

How should tar_scm do this?

> I think obs services should be as unintrusive as possible in that regard, as in I shouldn't have to alter the project config to use it.

Agree - But the selection of specific packages is a RPM or OBS topic

> That, or `glibc-all-langpacks` should be in the default value for the prjconf Prefer.

I would vote for the least overhead - so a minimal langpack should be selected. 
Anyway, the configuration could be done in the Fedora:34 project on OBS and all dependent projects will inherit.
