### ISSUE TITLE
.obscpio file format hex code means?

### ISSUE THREAD

**Issue by pyy** [openSUSE/obs-service-tar_scm#460]
Hello everyone,
I'm newer to obs. In each `root.obscpio` file, at the beginning of each reference filename, there are some Hex codes, for example, `07070100000000000081ED000003E80000006400000001607DCBD400000147000000000000000000000000000000000000002C00000000root/docker-entrypoint.d/30-populate-etc.sh`

also at the end of file, there is code `07070100000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000B00000000T`

May I ask what these hex code means? Thank you.

For example:
https://build.opensuse.org/package/view_file/openSUSE:Containers:Tumbleweed/php8-nginx-image.20230106101753/root.obscpio?expand=1

https://build.opensuse.org/package/view_file/openSUSE:Containers:Tumbleweed/opensuse-mariadb-image.20230106101745/root.obscpio?expand=1

**Comment by M0ses** [comment]
For questions like this, please ask in the OBS IRC channel or mailing-list as recommended here:
https://openbuildservice.org/support/
in future.

it is cpio newc format.
