### ISSUE TITLE
Files could not be expanded: service error (fatal: git upload-pack: not our...)

### ISSUE THREAD

**Issue by barathrm** [openSUSE/obs-service-tar_scm#495]
Hi all! Hope this is the right place for a bug report. I tried asking for help on the OBS chat, but to no avail.

I have a package which has started failing when triggering obs_scm with the following error

```
Files could not be expanded: service error: ' [less info](javascript:void(0))

service obs_scm failed:
time="2024-07-22T17:33:03Z" level=warning msg="Path \"/etc/SUSEConnect\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
time="2024-07-22T17:33:03Z" level=warning msg="Path \"/etc/zypp/credentials.d/SCCcredentials\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
Running /usr/lib/obs/service//obs_scm --scm git --url https://github.com/mooltipass/moolticute.git --filename moolticute-testing --package-meta yes --revision v1.03.17-testing --versionrewrite-pattern v([0-9\.]*)(-testing)?(.*) --versionrewrite-replacement \1\3 --versionformat @PARENT_TAG@.r@TAG_OFFSET@.g%h --outdir /var/cache/obs/MqHentC5VqjZ/out
Command ['git', 'reset', '--hard', 'v1.03.17-testing'] failed(128): 'warning: filtering not recognized by server, ignoring
warning: lazy fetching disabled; some objects may not be available
fatal: git upload-pack: not our ref 834bdab87037e0874c4f33a47193089bcec8ded8
fatal: remote error: upload-pack: not our ref 834bdab87037e0874c4f33a47193089bcec8ded8
fatal: unable to read tree ba0f3a03fc56e45a47e81e3acf27cee11fcfafbd
'
```

https://build.opensuse.org/package/show/home:fawz:mooltipass/moolticute-testing

Running the commands locally, and building the package locally using osc, works fine.

I assume there's some state left-over somewhere? The upstream git repo recently converted a subdirectory into a submodule, which may be to blame... 

Is there anything I can try?

**Comment by M0ses** [comment]
Thanks for opening this issue - I was writing a mail reply to your question on the mailing list.
I cleaned the cache and now [moolticute](https://build.opensuse.org/package/show/home:fawz:mooltipass/moolticute) works again

ATM I`m investigating in testing.

**Comment by k61n** [comment]
I have similar issue with https://build.opensuse.org/package/show/home:kholostov/qtisas

**Comment by ahmedmoselhi** [comment]
same issue here [snapd](https://build.opensuse.org/package/show/home:ahmedmoselhi2:branches:system:snappy/snapd-git)

**Comment by M0ses** [comment]
Seems like the package-meta option triggers the problem.
If you could disable it - this should be a first  workaround until I can release a final fix.

**Comment by haadr** [comment]
> Seems like the package-meta option triggers the problem. If you could disable it - this should be a first workaround until I can release a final fix.

Thanks, adding `<param name="package-meta">no</param>` worked! :pray:
