### ISSUE TITLE
How to handle this problem.

### ISSUE THREAD

**Issue by renzhengeek** [openSUSE/obs-service-tar_scm#65]
Hi all,
I use `osc service run` to download my project from github and to tar & compress it.

But what I got are a wrong named tar file and some error message.

The wrong named tar file is:  **_service:tar_scm**:ocfs2-test-1.0.4+git.1425366927.4243065.tar.
Obviously, if the tar file's name has not the prefix of "_service:tar_scm", everything is OK.

I don't know why I got this strange tar file name.Please give some advice.

The error message is:
```
n2:~/home:ZRen:branches:network:ha-clustering:Factory/ocfs2-test # osc service run 
Cloning into '/tmp/tmp__uzs5/tmpW2q6lt/ocfs2-test'...
HEAD is now at 4243065 Bring README back text format
Cleaning: /tmp/tmp__uzs5/tmpW2q6lt /tmp/tmp__uzs5/ocfs2-test-1.0.4+git.1425366927.4243065
ls: cannot access ocfs2-test*.tar: No such file or directory
ls: cannot access _service:*:ocfs2-test*.tar: No such file or directory
Unknown file ocfs2-test*.tar
Aborting: service call failed: /usr/lib/obs/service/recompress --file 'ocfs2-test*.tar' --compression 'bz2' --outdir /tmp/tmpVzmTUc
```
And my "_service" file is:
```
<services>
  <service name="tar_scm" mode="enabled">
    <param name="url">https://github.com/ganghe/ocfs2-test</param>
    <param name="scm">git</param>
    <param name="exclude">.git</param>
    <param name="versionformat">1.0.4+git.%ct.%h</param>
    <param name="revision">suse</param>
  </service>

  <service name="recompress" mode="enabled">
    <param name="file">ocfs2-test*.tar</param>
    <param name="compression">bz2</param>
  </service>

  <service name="set_version" mode="enabled">
    <param name="basename">ocfs2-test</param>
  </service>
```

**Comment by aspiers** [comment]
If you read the error message you can see that the failure comes from the `recompress` service, not `tar_scm`.  `recompress` is a very simple bash script so it should not be hard to debug, e.g. by adding `-x` to the first line of `/usr/lib/obs/service/recompress`.

**Comment by renzhengeek** [comment]
Sorry, but not sure you got the point.

tar_scm service got me a tar file with unnormal name.
The expected tar file name is  "ocfs2-test-1.0.4+git.1425366927.4243065.tar", but it got 
"_service:tar_scm:ocfs2-test-1.0.4+git.1425366927.4243065.tar".

So,recompress complain cannot find the tar file specified by "<param name="file">ocfs2-test*.tar</param>".

**Comment by aspiers** [comment]
No, that's nothing to do with `tar_scm`, it's how `osc` handles the temporary files generated during a source service run:

* https://github.com/openSUSE/osc/blob/master/osc/core.py#L414

Maybe you're using the wrong mode:

* http://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.source_service.html#idm140674037021520

Personally I always have `tar_scm` as a `disabled` service and then do `osc service disabledrun`.
