### ISSUE TITLE
Parent tag regex format issue

### ISSUE THREAD

**Issue by Grokzen** [openSUSE/obs-service-tar_scm#66]
Is there any reason why when i want to use `@PARENT_TAG@` it is required to have a dot after it? This enforcement prevents me from building a version string that have the tag followed by anything else, for example underscore `_`. 

Would it be possible to remove this limitation and only do a replacement on the `@PARENT_TAG@` ?

For example if i specify the following in `versionformat` 

```
<param name="versionformat">@PARENT_TAG@_%ct.%h</param>`
```

it will render to the following 

```
Version:       	1400180477.8d48089
```

But 

```
<param name="versionformat">@PARENT_TAG@.%ct.%h</param>`
```

it will render to the

```
Version:       	1.2.3.1400180477.8d48089
```

**Comment by aspiers** [comment]
I don't see anything in the code which could cause this.  Please can you confirm you can reproduce the problem with the latest code from the git `master` branch?

**Comment by Grokzen** [comment]
@aspiers I agree that the regex should not have broken it and for some unknown reason we got it to work in our environment so i guess i will close this issue as resolved somehow :] I think the problem was some other extension further in the build process, possible `set_version` but not sure.

**Comment by aspiers** [comment]
OK thanks for the update!
