### ISSUE TITLE
Does not work with OBS 2.6.1

### ISSUE THREAD

**Issue by kaltsi** [openSUSE/obs-service-tar_scm#69]
The .service file uses `<param>` elements, but OBS expects to find `<parameter>` elements. Added .service file check in OBS 2.6.1 results in an error when running _service.

**Comment by aspiers** [comment]
Oh dear.  Let me check I'm understanding this right - you are effectively saying that OBS recently changed the source service API in a way which wasn't backwards compatible, with no obvious deprecation warnings giving source service authors time to prepare for this change?

**Comment by kaltsi** [comment]
Well I hope I'm wrong, but I experienced this in my private OBS appliance installation. This commit on open-build-service openSUSE/open-build-service@e22d559b86d6b52b42571f3e3e42fc2499fd11ca adds a check to bs_service by using the readxml() call that was not there before. As a result my _service triggers started failing with 400: unknown element: param error.

Commenting out the two new lines in bs_service, or by renaming the `<param>` elements to `<parameter>` elements in tar_scm.service removes the error for me.

**Comment by aspiers** [comment]
Ah, thanks for the info!  I think this is simply a typo bug in that commit, which would make far more sense.  @adrianschroeter can you confirm?

**Comment by kaltsi** [comment]
It's not failing to the `die()` statement there, but the other one in the commit, the one that uses `readxml()`. Again, I may be wrong, but to me it seems that now the `tar_scm.service` file is validated. It was never validated before, as far as I can see.

The known/valid element names for the `tar_scm.service` (and any other .service) file are declared here https://github.com/openSUSE/open-build-service/blob/master/src/backend/BSXML.pm#L1309 and `param` is not there.

**Comment by adrianschroeter** [comment]
right, "param" is used in the _service file to use it. but "parameter" is used to define it in the declaration of a service in installed .service file.

The change in 2.6.1 is not meant to be incompatible, but it validates the used parameters now. IMHO the tar_scm .service file needs to be fixed here to use "parameter".

**Comment by adrianschroeter** [comment]
it may not be the best definition, but I actually want to stay compatible and the other service do use "parameter", so no way to change that in OBS side

**Comment by adrianschroeter** [comment]
btw, commit 70b9818d6d04f84f0aa96a2f7f7d38bb8a4089a3 broke it more or less on purpose .... it was correct before.

I fixed it in git now again.

**Comment by adrianschroeter** [comment]
updated also the package in openSUSE:Tools ... and will deploy it asap on build.opensuse.org ...

**Comment by Firef0x** [comment]
Hello, @adrianschroeter !

Excuse me, how often does the OBS server get updated to latest code? :confused:

Yours sincerely!

**Comment by kaltsi** [comment]
@adrianschroeter - the `<param>` elements are still used also in some other `obs-service-*` packages. In some cases there is mixed usage of `<param>` and `<parameter>`. Perhaps it's a good idea to check all of them at this time.

**Comment by adrianschroeter** [comment]
@kaltsi right, just fixed all of them where I have write access in git ....

@Firef0x: it happens when needed basically ... but we do follow our git master branch.

**Comment by aspiers** [comment]
@adrianschroeter thanks a lot for the info.  So this is a valid issue and pull requests to fix it are very welcome ;-)

**Comment by adrianschroeter** [comment]
already fixed it directly in git master and packages.
