### ISSUE TITLE
@TAG_OFFSET@ not expanded if @PARENT_TAG@ absent

### ISSUE THREAD

**Issue by luigino** [openSUSE/obs-service-tar_scm#75]
As per subject, @TAG_OFFSET@ cannot be used alone.

**Comment by aspiers** [comment]
Yes, that doesn't surprise me.  What behaviour do you see when you try to use it alone, and what would you ideally want to see instead?

**Comment by luigino** [comment]
> Files could not be expanded: service tar_scm failed:
> HEAD is now at  ...
> \e[0;31m@TAG_OFFSET@ can not be expanded\e[0m
> Cleaning: /var/tmp/obs_service/ ...

This is what I see.
I'd like to be able to hardcode a version number but keep the original tag offset.

**Comment by aspiers** [comment]
Sorry, I don't understand what you mean by "the original tag offset".  Can you give an example?

**Comment by luigino** [comment]
Sorry, I probably used the wrong terms.

I mean that, for example I have

    <param name="filename">name</param>
    <param name="versionformat">@PARENT_TAG@.@TAG_OFFSET@</param>

and obtain name-1.2git.5678

I'd like to be able to do:

    <param name="filename">name-2.0git.</param>
    <param name="versionformat">@TAG_OFFSET@</param>

to obtain name-2.0git.5678

I admit the case use is somewhat rare and possibly misleading,
but do you think such a thing could be feasible?

**Comment by aspiers** [comment]
It's not clear to me exactly what you want here, as there's no advantage to moving the tag string from `versionformat` to `filename`.  Or are you saying you want to manually specify which tag to use, and have `@TAG_OFFSET` calculated relative to that?  If so, then something like this should work fine:

```
<param name="filename">name</param>
<param name="versionformat">@PARENT_TAG@.@TAG_OFFSET@</param>
<param name="revision">2.0</param>
```

**Comment by luigino** [comment]
But whatf revision 2.0 doesn't actually exist?

What I'm trying to do here is to insert an arbitrary tag but keep the offset or at least the commit hash as reference.

I know it's bad form, but some projects are sloppy in that regard.

**Comment by aspiers** [comment]
Sorry, I still can't understand what you want.  Please can you be more precise?  What do you mean by "insert an arbitrary tag"?
