### ISSUE TITLE
Unwanted newline in generated SPEC files -> all my builds FAIL

### ISSUE THREAD

**Issue by martinrotter** [openSUSE/obs-service-tar_scm#88]
https://build.opensuse.org/package/view_file/home:skunkos:rssguard/rssguard-qt5/_service:set_version:rssguard-qt5.spec?expand=1

It affects almost all generated "script" files in my project except the Archlinux PKGBUILD which works fine.

Can you fix/help?

**Comment by toabctl** [comment]
@martinrotter you already reported this at https://github.com/openSUSE/obs-service-set_version/issues/26 . And it's a obs-service-set_version bug. Hopefully fixed but needs to be rolled out.

**Comment by martinrotter** [comment]
Okay, oh, just forgot I did.

Anyway, thx.
