### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by cfelder** [openSUSE/obs-service-tar_scm#91]
Just a short question: When are you planning the next release? It is some time ago when the previous release has been released.

Best
Christian

**Comment by cfelder** [comment]
*ping*

**Comment by cfelder** [comment]
any roadmap on the next release?

Best
Christian

**Comment by adrianschroeter** [comment]
There is a pre-0.6 package in openSUSE:Tools project which contains current master and some more stuff.

**Comment by cfelder** [comment]
Thanks for your feedback. I just updated our OBS instance to the most-recent package.

**Comment by aspiers** [comment]
Nevertheless I agree that I need to tag a new release - thanks for the reminder ;-)

**Comment by aspiers** [comment]
I'm currently going through all issues and PRs.  Next step after that would be to define some release milestones, which would help address this issue.

**Comment by aspiers** [comment]
I'm about to meet with @adrianschroeter and @M0ses, so we can form a plan around this finally.  Sorry for the wait.

**Comment by aspiers** [comment]
Looks like I need another reminder about this :-/ Had forgotten I'd promised to do it after #132 was merged.

**Comment by M0ses** [comment]
I updated openSUSE:Tools about a week ago

https://build.opensuse.org/package/revisions/openSUSE:Tools/obs-service-tar_scm

but there was no maintenance update.

**Comment by aspiers** [comment]
@M0ses I guess I should just tag a 0.7.0 now - any reason not to?

**Comment by aspiers** [comment]
@M0ses ping :-)

**Comment by M0ses** [comment]
@aspiers - AFAIK 0.8.0 has been already released and I`m fine to release 0.9.0 - but before you might want to review https://github.com/openSUSE/obs-service-tar_scm/pull/224 as proxy support was already requested in the past and I think it`s an valuable PR for the next release.

**Comment by aspiers** [comment]
@M0ses It's not officially released until there's a tag for it, and the newest tag is still 0.6.0 from 2 years ago.  That's why we get issues like #226.  If you have released newer code in OBS then please retroactively add the tags for each of those versions.  Thanks!

**Comment by M0ses** [comment]
@aspiers: ok I will try to find out, when we released the last 2 "package-versions" and add tags here if succeed. For the next release "0.9.0" I would like to add 2 more feature PRs #191 and #224

**Comment by aspiers** [comment]
@M0ses Thanks for the info! Please let's use GitHub milestones for tracking releases, it's really useful.

**Comment by M0ses** [comment]
@aspiers  - I tried to add the tags aligned to the versions released in OBS - could you please check and give feedback?

**Comment by M0ses** [comment]
Just added tag 0.9.0 in branch master and updated packages in openSUSE:Tools.
Package has got maintenance release to 0.8.0 in the past.
Versions/Tags should be aligned.
Closing now as it seems to outdated anyway.
