### ISSUE TITLE
v-prefixed tags in git

### ISSUE THREAD

**Issue by matwey** [openSUSE/obs-service-tar_scm#92]
Hello,

I am sorry if this already has been discussed, or I missed something.
Some developers are used v-prefixed tags for versions, for instance `v0.4.5`, when `@PARENT_TAG@` is used, `tar_scm` creates an archive like the following `repo-v0.4.5.tar.gz`.
Which is incompatible with `set_version` which thinks that the version is `v0.4.5` and writes:

```
Version: v0.4.5
```

to the spec file.

**Comment by hurricanehrndz** [comment]
This occurs with debian builds as well, setversion just seems to be ignored and will not run.

**Comment by M0ses** [comment]
This should be fixed with the new parameters

* versionrewrite-pattern
* versionrewrite-replacement

https://github.com/openSUSE/obs-service-tar_scm/commit/960d0cebad3bbf86102991eb38c542bbf5a16df4#diff-defb394841429cd7c4b5ad43737277e1R64
